/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Dialogs;

import DAO.DeviceDAO;
import Models.Device;

/**
 *
 * @author GerardoAGL
 */
public class Fault extends javax.swing.JDialog {
    
    public Models.Fault fault;
    /**
     * Creates new form Fault
     */
    public Fault(java.awt.Frame parent, boolean modal, Models.Fault fault) {
        super(parent, modal);
        initComponents();
        
        this.fault = fault;
        Device device = DeviceDAO.deviceById(this.fault.getDevice());
        
        lbl_title.setText("Avería n° "+ fault.getCode());
        lbl_date.setText("Fecha de avería: "+ fault.getFaultDate());
        lbl_device.setText("Dispositivo: "+device.getModel()+" "+device.getBrand());
        txt_info.setText(fault.getInfo());
        if(fault.isFixed()){            
            lbl_soldate.setText("Fecha de reparacion: "+fault.getSolutionDate());
            lbl_cost.setText("Costo de reparación: "+fault.getCost());
            txt_sol.setText(fault.getSolution());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_device = new javax.swing.JLabel();
        lbl_info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_info = new javax.swing.JTextArea();
        lbl_soldate = new javax.swing.JLabel();
        lbl_cost = new javax.swing.JLabel();
        lbl_sol = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_sol = new javax.swing.JTextArea();
        btn_accept = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));

        lbl_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lbl_title.setText("Avería n°");

        lbl_date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_date.setText("Fecha de avería:");

        lbl_device.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_device.setText("Dispositivo:");

        lbl_info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_info.setText("Información de avería:");

        jScrollPane1.setBorder(null);

        txt_info.setEditable(false);
        txt_info.setColumns(20);
        txt_info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info.setRows(5);
        jScrollPane1.setViewportView(txt_info);

        lbl_soldate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_soldate.setText("Fecha de reparación: (Aún no se ha reparado el dispositivo)");

        lbl_cost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cost.setText("Costo de reparación:");

        lbl_sol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_sol.setText("Información de reparación:");

        jScrollPane2.setBorder(null);

        txt_sol.setEditable(false);
        txt_sol.setColumns(20);
        txt_sol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sol.setRows(5);
        txt_sol.setText("\n");
        jScrollPane2.setViewportView(txt_sol);

        btn_accept.setBackground(new java.awt.Color(0, 145, 234));
        btn_accept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_accept.setText("Aceptar");
        btn_accept.setToolTipText("accept");
        btn_accept.setOpaque(true);

        javax.swing.GroupLayout pnl_backgroundLayout = new javax.swing.GroupLayout(pnl_background);
        pnl_background.setLayout(pnl_backgroundLayout);
        pnl_backgroundLayout.setHorizontalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_device, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(lbl_soldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(lbl_sol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_backgroundLayout.setVerticalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addComponent(lbl_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_device)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_soldate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_cost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_sol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_accept;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_cost;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_device;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JLabel lbl_sol;
    private javax.swing.JLabel lbl_soldate;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JTextArea txt_info;
    private javax.swing.JTextArea txt_sol;
    // End of variables declaration//GEN-END:variables
}
