/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Validations.UserName;
import DAO.CategoryDAO;
import Models.Category;
import Models.Characteristic;
import Views.Decorations.TextHint;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author GerardoAGL
 */
public class AddDevice extends javax.swing.JFrame {
    
    public DefaultListModel dlmCha;
    public DefaultListModel dlmApp;
    public Category categories[];
    public ArrayList<Characteristic> characteristic; 
    public ArrayList<String> apps;
    public BufferedImage picture = null;
    
    /**
     * Creates new form AddClass
     */
    
    public AddDevice() {
        
        initComponents();
        characteristic = new ArrayList<Characteristic>();
        apps = new ArrayList<String>();
        
        dlmCha = new DefaultListModel();
        dlmApp = new DefaultListModel();
        
        lst_cha.setModel(dlmCha);
        lst_app.setModel(dlmApp);
        
        categories = CategoryDAO.all();
        
        for(int i = 0; i < categories.length; i++){
           cb_type.addItem(categories[i].getName());
        }        
        cb_typeItemStateChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnl_bg = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_model = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_type = new javax.swing.JLabel();
        cb_type = new javax.swing.JComboBox<>();
        lbl_charact = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_cha = new javax.swing.JList<>();
        btn_save = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();
        app_add = new javax.swing.JLabel();
        cha_remove = new javax.swing.JLabel();
        lbl_apps = new javax.swing.JLabel();
        app_remove = new javax.swing.JLabel();
        cha_add = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_app = new javax.swing.JList<>();
        btn_picture = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_bg.setBackground(new java.awt.Color(255, 255, 255));

        lbl_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lbl_title.setText("Agregar Dispositivo");

        txt_brand.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_brand.setForeground(new java.awt.Color(102, 102, 102));
        txt_brand.setText("Marca");
        txt_brand.setBorder(null);
        txt_brand.addKeyListener(new UserName());

        jSeparator1.setBackground(new java.awt.Color(0, 145, 234));
        jSeparator1.setForeground(new java.awt.Color(0, 145, 234));

        txt_model.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_model.setForeground(new java.awt.Color(102, 102, 102));
        txt_model.setText("Modelo");
        txt_model.setBorder(null);
        txt_model.addKeyListener(new UserName());

        jSeparator2.setBackground(new java.awt.Color(0, 145, 234));
        jSeparator2.setForeground(new java.awt.Color(0, 145, 234));

        lbl_type.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_type.setText("Tipo");

        cb_type.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_type.setBorder(null);
        cb_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_typeItemStateChanged(evt);
            }
        });

        lbl_charact.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_charact.setText("Caracteristicas");

        lst_cha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 145, 234)));
        jScrollPane1.setViewportView(lst_cha);

        btn_save.setBackground(new java.awt.Color(0, 145, 234));
        btn_save.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_save.setText("Guardar");
        btn_save.setToolTipText("save add");
        btn_save.setOpaque(true);

        btn_cancel.setBackground(new java.awt.Color(213, 0, 0));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cancel.setText("Cancelar");
        btn_cancel.setToolTipText("cancel add");
        btn_cancel.setOpaque(true);

        app_add.setBackground(new java.awt.Color(255, 255, 255));
        app_add.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        app_add.setForeground(new java.awt.Color(0, 145, 234));
        app_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app_add.setText("+");
        app_add.setToolTipText("addApp");

        cha_remove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cha_remove.setForeground(new java.awt.Color(213, 0, 0));
        cha_remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cha_remove.setText("-");
        cha_remove.setToolTipText("removeCha");

        lbl_apps.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_apps.setText("Aplicaciones");

        app_remove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_remove.setForeground(new java.awt.Color(213, 0, 0));
        app_remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app_remove.setText("-");
        app_remove.setToolTipText("removeApp");

        cha_add.setBackground(new java.awt.Color(255, 255, 255));
        cha_add.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cha_add.setForeground(new java.awt.Color(0, 145, 234));
        cha_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cha_add.setText("+");
        cha_add.setToolTipText("addCha");

        lst_app.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 145, 234)));
        lst_app.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(lst_app);

        btn_picture.setBackground(new java.awt.Color(117, 117, 117));
        btn_picture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_picture.setForeground(new java.awt.Color(255, 255, 255));
        btn_picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_picture.setText("Foto");
        btn_picture.setToolTipText("picture");
        btn_picture.setDoubleBuffered(true);
        btn_picture.setOpaque(true);

        javax.swing.GroupLayout pnl_bgLayout = new javax.swing.GroupLayout(pnl_bg);
        pnl_bg.setLayout(pnl_bgLayout);
        pnl_bgLayout.setHorizontalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(lbl_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bgLayout.createSequentialGroup()
                        .addComponent(lbl_apps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(app_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(app_add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(pnl_bgLayout.createSequentialGroup()
                        .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_brand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_model)
                            .addComponent(jSeparator2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bgLayout.createSequentialGroup()
                        .addComponent(lbl_charact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_bgLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(cha_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cha_add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btn_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_bgLayout.setVerticalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addComponent(lbl_type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cha_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cha_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_charact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_apps, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(app_remove)
                        .addComponent(app_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txt_brand.addFocusListener(new TextHint(txt_brand, "Marca"));
        txt_model.addFocusListener(new TextHint(txt_model, "Modelo"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_typeItemStateChanged
        // TODO add your handling code here:
        Category category = categories[cb_type.getSelectedIndex()];
        if(category.hasApps()){
            lst_app.setEnabled(true);
        }else{
            dlmApp.removeAllElements();
            apps.clear();
            lst_app.setEnabled(false);
        }
    }//GEN-LAST:event_cb_typeItemStateChanged
    
    private void cb_typeItemStateChanged() {                                         
        // TODO add your handling code here:
        Category category = categories[cb_type.getSelectedIndex()];
        if(category.hasApps()){
            lst_app.setEnabled(true);
        }else{
            dlmApp.removeAllElements();
            apps.clear();
            lst_app.setEnabled(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel app_add;
    public javax.swing.JLabel app_remove;
    public javax.swing.JLabel btn_cancel;
    public javax.swing.JLabel btn_picture;
    public javax.swing.JLabel btn_save;
    public javax.swing.JComboBox<String> cb_type;
    public javax.swing.JLabel cha_add;
    public javax.swing.JLabel cha_remove;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_apps;
    private javax.swing.JLabel lbl_charact;
    public javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_type;
    public javax.swing.JList<String> lst_app;
    public javax.swing.JList<String> lst_cha;
    private javax.swing.JPanel pnl_bg;
    public javax.swing.JTextField txt_brand;
    public javax.swing.JTextField txt_model;
    // End of variables declaration//GEN-END:variables
}
