/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.DeviceDAO;
import DAO.PersonDAO;
import Views.Decorations.Colors;

/**
 *
 * @author GerardoAGL
 */
public class Assignment extends javax.swing.JFrame {
    
    public Models.Assignment assignment;
    /**
     * Creates new form Assignment
     */
    public Assignment(Models.Assignment assignment) {
        initComponents();
        this.assignment = assignment;
        Models.Device device = DeviceDAO.deviceById(assignment.getDevice());
        Models.Persona person = PersonDAO.personById(assignment.getPerson());
        
        lbl_title.setText("Nro de asignación: " + this.assignment.getId());
        lbl_date.setText("Fecha de asignación: " + this.assignment.getDate());
        lbl_person.setText("Trabajador: " + person.getNombre() + " " + person.getCedula());
        lbl_device.setText("Dispositivo: " + device.getBrand() + " " + device.getModel());
        lbl_departament.setText("Departamento: " + this.assignment.getDepartament());
        
        if(this.assignment.getDevolutionDate() != null){
            lbl_status.setBackground(Colors.green());
            lbl_status.setText("Entregado");
            lbl_devdate.setText("Fecha de devolución: " + this.assignment.getDevolutionDate());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_person = new javax.swing.JLabel();
        lbl_device = new javax.swing.JLabel();
        lbl_departament = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_devdate = new javax.swing.JLabel();
        btn_accept = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));

        lbl_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lbl_title.setText("Nro de asignación: ");
        lbl_title.setToolTipText("");

        lbl_date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_date.setText("Fecha de asignación:");

        lbl_person.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_person.setText("Trabajador:");

        lbl_device.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_device.setText("Dispositivo:");
        lbl_device.setToolTipText("");

        lbl_departament.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_departament.setText("Departamento:");
        lbl_departament.setToolTipText("");

        lbl_status.setBackground(new java.awt.Color(213, 0, 0));
        lbl_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        lbl_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_status.setText("Pendiente de Entrega");
        lbl_status.setToolTipText("");
        lbl_status.setOpaque(true);

        lbl_devdate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_devdate.setText("Fecha de devolución:");
        lbl_devdate.setToolTipText("");

        btn_accept.setBackground(new java.awt.Color(0, 145, 234));
        btn_accept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_accept.setText("Aceptar");
        btn_accept.setToolTipText("accept");
        btn_accept.setOpaque(true);

        javax.swing.GroupLayout pnl_backgroundLayout = new javax.swing.GroupLayout(pnl_background);
        pnl_background.setLayout(pnl_backgroundLayout);
        pnl_backgroundLayout.setHorizontalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_person, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_device, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_devdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_departament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_backgroundLayout.setVerticalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_person)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_device)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_departament)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lbl_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lbl_devdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_accept;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_departament;
    private javax.swing.JLabel lbl_devdate;
    private javax.swing.JLabel lbl_device;
    private javax.swing.JLabel lbl_person;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_background;
    // End of variables declaration//GEN-END:variables
}
