/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Departament;
import Models.Persona;

/**
 *
 * @author GerardoAGL
 */
public class AssignDevice extends javax.swing.JFrame {
    
    public Persona person;
    public Models.Device device;
    /**
     * Creates new form AssignDevice
     */
    public AssignDevice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_person = new javax.swing.JLabel();
        btn_person = new javax.swing.JLabel();
        lbl_device = new javax.swing.JLabel();
        btn_device = new javax.swing.JLabel();
        btn_accept = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();
        lbl_departament = new javax.swing.JLabel();
        cb_departament = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));

        lbl_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lbl_title.setText("Asignar dispositivo");
        lbl_title.setToolTipText("");

        lbl_person.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_person.setText("Buscar persona");

        btn_person.setBackground(new java.awt.Color(117, 117, 117));
        btn_person.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_person.setForeground(new java.awt.Color(255, 255, 255));
        btn_person.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_person.setText("...");
        btn_person.setToolTipText("person");
        btn_person.setOpaque(true);

        lbl_device.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_device.setText("Buscar dispositivo");

        btn_device.setBackground(new java.awt.Color(117, 117, 117));
        btn_device.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_device.setForeground(new java.awt.Color(255, 255, 255));
        btn_device.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_device.setText("...");
        btn_device.setToolTipText("device");
        btn_device.setOpaque(true);

        btn_accept.setBackground(new java.awt.Color(0, 145, 234));
        btn_accept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_accept.setText("Aceptar");
        btn_accept.setToolTipText("accept");
        btn_accept.setOpaque(true);

        btn_cancel.setBackground(new java.awt.Color(213, 0, 0));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cancel.setText("Cancelar");
        btn_cancel.setToolTipText("cancel");
        btn_cancel.setOpaque(true);

        lbl_departament.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_departament.setText("Departamento");

        cb_departament.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_departament.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informática", "Diseño", "Marketing", "Gerencial", "Administración", "Robotica" }));

        javax.swing.GroupLayout pnl_backgroundLayout = new javax.swing.GroupLayout(pnl_background);
        pnl_background.setLayout(pnl_backgroundLayout);
        pnl_backgroundLayout.setHorizontalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_departament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(pnl_backgroundLayout.createSequentialGroup()
                        .addComponent(lbl_person, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_person, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_backgroundLayout.createSequentialGroup()
                        .addComponent(lbl_device, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_device, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_departament, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_backgroundLayout.setVerticalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addGap(27, 27, 27)
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_person)
                    .addComponent(btn_person))
                .addGap(18, 18, 18)
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_device)
                    .addComponent(btn_device))
                .addGap(18, 18, 18)
                .addComponent(lbl_departament)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_departament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_accept;
    public javax.swing.JLabel btn_cancel;
    public javax.swing.JLabel btn_device;
    public javax.swing.JLabel btn_person;
    public javax.swing.JComboBox<String> cb_departament;
    private javax.swing.JLabel lbl_departament;
    public javax.swing.JLabel lbl_device;
    public javax.swing.JLabel lbl_person;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_background;
    // End of variables declaration//GEN-END:variables
}
