/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.CategoryDAO;
import Models.Category;
import Views.Decorations.Colors;
import Views.Decorations.ImageBorder;

/**
 *
 * @author GerardoAGL
 */
public class Device extends javax.swing.JFrame {
    
    public Models.Device device;
    /**
     * Creates new form Device
     */
    public Device(Models.Device device) {
        initComponents();
        
        this.device = device;
        initLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_categ = new javax.swing.JLabel();
        pnl_container = new javax.swing.JPanel();
        lbl_condition = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        btn_cha = new javax.swing.JLabel();
        btn_apps = new javax.swing.JLabel();
        btn_accept = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));

        lbl_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lbl_title.setText("Título");

        lbl_categ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_categ.setText("categoría");

        javax.swing.GroupLayout pnl_containerLayout = new javax.swing.GroupLayout(pnl_container);
        pnl_container.setLayout(pnl_containerLayout);
        pnl_containerLayout.setHorizontalGroup(
            pnl_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_containerLayout.setVerticalGroup(
            pnl_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        lbl_condition.setBackground(new java.awt.Color(0, 0, 0));
        lbl_condition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_condition.setForeground(new java.awt.Color(255, 255, 255));
        lbl_condition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_condition.setText("Estado");
        lbl_condition.setToolTipText("");
        lbl_condition.setOpaque(true);

        lbl_status.setBackground(new java.awt.Color(0, 0, 0));
        lbl_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        lbl_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_status.setText("Situacion");
        lbl_status.setToolTipText("");
        lbl_status.setOpaque(true);

        btn_cha.setBackground(new java.awt.Color(117, 117, 117));
        btn_cha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cha.setForeground(new java.awt.Color(255, 255, 255));
        btn_cha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cha.setText("Caracteristicas");
        btn_cha.setToolTipText("characteristics");
        btn_cha.setOpaque(true);

        btn_apps.setBackground(new java.awt.Color(117, 117, 117));
        btn_apps.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_apps.setForeground(new java.awt.Color(255, 255, 255));
        btn_apps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_apps.setText("Aplicaciones");
        btn_apps.setToolTipText("apps");
        btn_apps.setOpaque(true);

        btn_accept.setBackground(new java.awt.Color(0, 145, 234));
        btn_accept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_accept.setText("Aceptar");
        btn_accept.setToolTipText("accept");
        btn_accept.setOpaque(true);

        javax.swing.GroupLayout pnl_backgroundLayout = new javax.swing.GroupLayout(pnl_background);
        pnl_background.setLayout(pnl_backgroundLayout);
        pnl_backgroundLayout.setHorizontalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_categ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_container, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_condition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_backgroundLayout.createSequentialGroup()
                        .addComponent(btn_cha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_apps, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(pnl_backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_backgroundLayout.setVerticalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_categ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_condition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_status)
                .addGap(18, 18, 18)
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cha, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_apps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void initLabels(){
        
        String condition = device.getCondition();
        String status = device.getStatus();
        Category category = CategoryDAO.searchById(device.getCategory());
                
        lbl_title.setText(device.getBrand() +" "+device.getModel());
        lbl_categ.setText(category.getName());
        if(condition.equals("Funcional"))
            lbl_condition.setBackground(Colors.green());
        else
            lbl_condition.setBackground(Colors.red());
        
        if(status.equals("Disponible"))
            lbl_status.setBackground(Colors.green());
        else
            lbl_status.setBackground(Colors.red());
        
        lbl_condition.setText(condition);
        lbl_status.setText(status);
       
        if(device.getPhoto() != null)
            pnl_container.setBorder(new ImageBorder(device.getPhoto()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_accept;
    public javax.swing.JLabel btn_apps;
    public javax.swing.JLabel btn_cha;
    private javax.swing.JLabel lbl_categ;
    private javax.swing.JLabel lbl_condition;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_container;
    // End of variables declaration//GEN-END:variables
}
