/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.DeviceDAO;
import Views.Decorations.Colors;

/**
 *
 * @author GerardoAGL
 */
public class Fault extends javax.swing.JFrame {

    /**
     * Creates new form Fault
     */
    public Fault(Models.Fault fault) {
        initComponents();
        Models.Device device = DeviceDAO.deviceById(fault.getDevice());
        
        lbl_title.setText("Reporte n° "+fault.getCode());
        lbl_date.setText("Fecha de avería: "+fault.getFaultDate());
        lbl_device.setText("Dispositivo: "+device.getBrand()+" "+device.getModel());
        txt_diag.setText(fault.getInfo());
        if(fault.isFixed()){
            lbl_status.setBackground(Colors.green());
            lbl_status.setText("Reparado");
            lbl_soldate.setText("Fecha de reparación: " +fault.getSolutionDate());
            txt_sol.setText(fault.getSolution());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_device = new javax.swing.JLabel();
        lbl_diag = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_diag = new javax.swing.JTextArea();
        lbl_status = new javax.swing.JLabel();
        lbl_soldate = new javax.swing.JLabel();
        lbl_sol = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_sol = new javax.swing.JTextArea();
        btn_accept = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));

        lbl_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lbl_title.setText("Reporte n°");

        lbl_date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_date.setText("Fecha de avería:");

        lbl_device.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_device.setText("Dispositivo: ");

        lbl_diag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_diag.setText("Diagnostico:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 117, 117)));

        txt_diag.setEditable(false);
        txt_diag.setColumns(20);
        txt_diag.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_diag.setRows(5);
        jScrollPane1.setViewportView(txt_diag);

        lbl_status.setBackground(new java.awt.Color(213, 0, 0));
        lbl_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        lbl_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_status.setText("Pendiente de reparación");
        lbl_status.setOpaque(true);

        lbl_soldate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_soldate.setText("Fecha de reparación: aun no se ha solucionado");

        lbl_sol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_sol.setText("Solución:");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 117, 117)));

        txt_sol.setEditable(false);
        txt_sol.setColumns(20);
        txt_sol.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_sol.setRows(5);
        jScrollPane2.setViewportView(txt_sol);

        btn_accept.setBackground(new java.awt.Color(0, 145, 234));
        btn_accept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_accept.setText("Aceptar");
        btn_accept.setToolTipText("accept");
        btn_accept.setOpaque(true);

        javax.swing.GroupLayout pnl_backgroundLayout = new javax.swing.GroupLayout(pnl_background);
        pnl_background.setLayout(pnl_backgroundLayout);
        pnl_backgroundLayout.setHorizontalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_device, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_diag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(lbl_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_soldate, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(lbl_sol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_backgroundLayout.setVerticalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_device)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_diag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_soldate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_sol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_accept;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_device;
    private javax.swing.JLabel lbl_diag;
    private javax.swing.JLabel lbl_sol;
    private javax.swing.JLabel lbl_soldate;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JTextArea txt_diag;
    private javax.swing.JTextArea txt_sol;
    // End of variables declaration//GEN-END:variables
}
