/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Validations.NumberInteger;
import DAO.DeviceDAO;
import Models.Fault;
import Views.Decorations.TextHint;

/**
 *
 * @author GerardoAGL
 */
public class FixFault extends javax.swing.JFrame {
    
    public Fault fault;
    /**
     * Creates new form FixFault
     */
    public FixFault(Fault fault) {
        initComponents();
        
        this.fault = fault;
        Models.Device device = DeviceDAO.deviceById(fault.getDevice());
        
        lbl_code.setText("Códio de avería: "+this.fault.getCode());
        lbl_device.setText("Dispositivo: " + device.getModel());
        lbl_date.setText("Fecha de avería: "+this.fault.getFaultDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_code = new javax.swing.JLabel();
        lbl_device = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        txt_cost = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_solution = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_solution = new javax.swing.JTextArea();
        btn_accept = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_background.setBackground(new java.awt.Color(255, 255, 255));

        lbl_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lbl_title.setText("Dispositivo arreglado");
        lbl_title.setToolTipText("");

        lbl_code.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_code.setText("Código de avería:");
        lbl_code.setToolTipText("");

        lbl_device.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_device.setText("Dispositivo:");
        lbl_device.setToolTipText("");

        lbl_date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_date.setText("Fecha de avería:");
        lbl_date.setToolTipText("");

        txt_cost.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_cost.setForeground(new java.awt.Color(102, 102, 102));
        txt_cost.setText("Costo de reparación (Bsf)");
        txt_cost.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 145, 234));
        jSeparator1.setForeground(new java.awt.Color(0, 145, 234));

        lbl_solution.setText("Información");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 145, 234), 2));

        txt_solution.setColumns(20);
        txt_solution.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_solution.setForeground(new java.awt.Color(102, 102, 102));
        txt_solution.setRows(5);
        txt_solution.setText("Ej: Se cambió el disco duro");
        txt_solution.setBorder(null);
        jScrollPane1.setViewportView(txt_solution);
        txt_solution.addFocusListener(new TextHint(txt_solution, "Ej: Se cambió el disco duro"));

        btn_accept.setBackground(new java.awt.Color(0, 145, 234));
        btn_accept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_accept.setForeground(new java.awt.Color(255, 255, 255));
        btn_accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_accept.setText("Aceptar");
        btn_accept.setToolTipText("accept fix");
        btn_accept.setOpaque(true);

        btn_cancel.setBackground(new java.awt.Color(213, 0, 0));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cancel.setText("Cancelar");
        btn_cancel.setToolTipText("cancel fix");
        btn_cancel.setOpaque(true);

        javax.swing.GroupLayout pnl_backgroundLayout = new javax.swing.GroupLayout(pnl_background);
        pnl_background.setLayout(pnl_backgroundLayout);
        pnl_backgroundLayout.setHorizontalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(lbl_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_device, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cost)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addComponent(lbl_solution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_backgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_backgroundLayout.setVerticalGroup(
            pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addComponent(lbl_code)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_device)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_date)
                .addGap(18, 18, 18)
                .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_solution)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnl_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_cost.addFocusListener(new TextHint(txt_cost, "Costo de reparación (Bsf)"));
        txt_cost.addKeyListener(new NumberInteger());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_accept;
    public javax.swing.JLabel btn_cancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_code;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_device;
    private javax.swing.JLabel lbl_solution;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_background;
    public javax.swing.JTextField txt_cost;
    public javax.swing.JTextArea txt_solution;
    // End of variables declaration//GEN-END:variables
}
