/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Views.Decorations.Colors;
import Views.Dialogs.AddUser;
import Views.Dialogs.EditUser;
import Views.Dialogs.DeleteUser;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.WindowConstants;

/**
 *
 * @author GerardoAGL
 */
public class Main extends javax.swing.JFrame {
    
    private String username;
    /**
     * Creates new form Main
     */
    
    public Main(String username){
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bg = new javax.swing.JPanel();
        pnl_nav = new javax.swing.JPanel();
        lbl_users = new javax.swing.JLabel();
        lbl_devices = new javax.swing.JLabel();
        lbl_reports = new javax.swing.JLabel();
        lbl_contacts = new javax.swing.JLabel();
        lbl_storehouse = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        pnl_cont = new javax.swing.JPanel();
        spnl_user = new javax.swing.JScrollPane();
        users = new javax.swing.JPanel();
        usersTitle = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        usersOp4 = new javax.swing.JPanel();
        lbl_op11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usersOp5 = new javax.swing.JPanel();
        lbl_op12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usersOp6 = new javax.swing.JPanel();
        lbl_op13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usersOp7 = new javax.swing.JPanel();
        lbl_op14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnl_device = new javax.swing.JScrollPane();
        devices = new javax.swing.JPanel();
        deviceTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        deviceOp1 = new javax.swing.JPanel();
        lbl_op21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deviceOp2 = new javax.swing.JPanel();
        lbl_op22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deviceOp3 = new javax.swing.JPanel();
        lbl_op23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        deviceOp4 = new javax.swing.JPanel();
        lbl_op24 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        deviceOp5 = new javax.swing.JPanel();
        lbl_op25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        deviceOp6 = new javax.swing.JPanel();
        lbl_op26 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        deviceOp7 = new javax.swing.JPanel();
        lbl_op27 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        deviceOp8 = new javax.swing.JPanel();
        lbl_op28 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spnl_reports = new javax.swing.JScrollPane();
        reports = new javax.swing.JPanel();
        reportTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reportOp1 = new javax.swing.JPanel();
        lbl_op31 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        reportOp2 = new javax.swing.JPanel();
        lbl_op32 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        reportOp3 = new javax.swing.JPanel();
        lbl_op33 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        spnl_contacts = new javax.swing.JScrollPane();
        contacts = new javax.swing.JPanel();
        contacts_img = new javax.swing.JLabel();
        contacts_title = new javax.swing.JLabel();
        contactsOp1 = new javax.swing.JPanel();
        lbl_op41 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        contactsOp2 = new javax.swing.JPanel();
        lbl_op42 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        contactsOp3 = new javax.swing.JPanel();
        lbl_op43 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spnl_storehouse = new javax.swing.JScrollPane();
        storehouse = new javax.swing.JPanel();
        storehouse_img = new javax.swing.JLabel();
        storehouse_title = new javax.swing.JLabel();
        storehouseOp1 = new javax.swing.JPanel();
        lbl_op51 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        pnl_bg.setBackground(new java.awt.Color(255, 255, 255));
        pnl_bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 117, 117)));

        pnl_nav.setBackground(new java.awt.Color(0, 99, 177));

        lbl_users.setBackground(new java.awt.Color(33, 150, 243));
        lbl_users.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbl_users.setForeground(new java.awt.Color(255, 255, 255));
        lbl_users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_users.setText("Usuarios");
        lbl_users.setToolTipText("user");
        lbl_users.setOpaque(true);

        lbl_devices.setBackground(new java.awt.Color(0, 99, 177));
        lbl_devices.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbl_devices.setForeground(new java.awt.Color(255, 255, 255));
        lbl_devices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_devices.setText("Dispositivos");
        lbl_devices.setToolTipText("devices");
        lbl_devices.setOpaque(true);

        lbl_reports.setBackground(new java.awt.Color(0, 99, 177));
        lbl_reports.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbl_reports.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_reports.setText("Reportes");
        lbl_reports.setToolTipText("reports");
        lbl_reports.setOpaque(true);

        lbl_contacts.setBackground(new java.awt.Color(0, 99, 177));
        lbl_contacts.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbl_contacts.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contacts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_contacts.setText("Contactos");
        lbl_contacts.setToolTipText("contacts");
        lbl_contacts.setOpaque(true);

        lbl_storehouse.setBackground(new java.awt.Color(0, 99, 177));
        lbl_storehouse.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbl_storehouse.setForeground(new java.awt.Color(255, 255, 255));
        lbl_storehouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_storehouse.setText("Almacen");
        lbl_storehouse.setToolTipText("storehouse");
        lbl_storehouse.setOpaque(true);

        lbl_logout.setBackground(new java.awt.Color(213, 0, 0));
        lbl_logout.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logout.setText("Cerrar sesión");
        lbl_logout.setToolTipText("logout");
        lbl_logout.setOpaque(true);

        javax.swing.GroupLayout pnl_navLayout = new javax.swing.GroupLayout(pnl_nav);
        pnl_nav.setLayout(pnl_navLayout);
        pnl_navLayout.setHorizontalGroup(
            pnl_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_users, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_devices, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_storehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_navLayout.setVerticalGroup(
            pnl_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_navLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_users, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_devices, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_storehouse))
                .addContainerGap())
        );

        pnl_cont.setBackground(new java.awt.Color(255, 255, 255));
        pnl_cont.setLayout(new java.awt.CardLayout());

        spnl_user.setBorder(null);

        users.setBackground(new java.awt.Color(255, 255, 255));

        usersTitle.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        usersTitle.setText("Usuarios");

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/user-icon.png"))); // NOI18N

        usersOp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersOp4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersOp4MouseExited(evt);
            }
        });

        lbl_op11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op11.setText("Agregar trabajador");
        lbl_op11.setToolTipText("add person");
        lbl_op11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_op11MouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/adduser.png"))); // NOI18N

        javax.swing.GroupLayout usersOp4Layout = new javax.swing.GroupLayout(usersOp4);
        usersOp4.setLayout(usersOp4Layout);
        usersOp4Layout.setHorizontalGroup(
            usersOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersOp4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op11, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        usersOp4Layout.setVerticalGroup(
            usersOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersOp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op11)
                .addContainerGap())
        );

        usersOp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersOp5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersOp5MouseExited(evt);
            }
        });

        lbl_op12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op12.setText("Información de trabajador");
        lbl_op12.setToolTipText("info person");
        lbl_op12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_op12MouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/seeuser.png"))); // NOI18N

        javax.swing.GroupLayout usersOp5Layout = new javax.swing.GroupLayout(usersOp5);
        usersOp5.setLayout(usersOp5Layout);
        usersOp5Layout.setHorizontalGroup(
            usersOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersOp5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersOp5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_op12, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        usersOp5Layout.setVerticalGroup(
            usersOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersOp5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op12)
                .addContainerGap())
        );

        usersOp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersOp6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersOp6MouseExited(evt);
            }
        });

        lbl_op13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op13.setText("Editar trabajador");
        lbl_op13.setToolTipText("edit person");
        lbl_op13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_op13MouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/edituser.png"))); // NOI18N

        javax.swing.GroupLayout usersOp6Layout = new javax.swing.GroupLayout(usersOp6);
        usersOp6.setLayout(usersOp6Layout);
        usersOp6Layout.setHorizontalGroup(
            usersOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersOp6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op13, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usersOp6Layout.setVerticalGroup(
            usersOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersOp6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lbl_op13)
                .addContainerGap())
        );

        usersOp7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersOp7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersOp7MouseExited(evt);
            }
        });

        lbl_op14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op14.setText("Eliminar trabajador");
        lbl_op14.setToolTipText("delete person");
        lbl_op14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_op14MouseExited(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/deleteuser.png"))); // NOI18N

        javax.swing.GroupLayout usersOp7Layout = new javax.swing.GroupLayout(usersOp7);
        usersOp7.setLayout(usersOp7Layout);
        usersOp7Layout.setHorizontalGroup(
            usersOp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersOp7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersOp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op14, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        usersOp7Layout.setVerticalGroup(
            usersOp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersOp7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lbl_op14)
                .addContainerGap())
        );

        javax.swing.GroupLayout usersLayout = new javax.swing.GroupLayout(users);
        users.setLayout(usersLayout);
        usersLayout.setHorizontalGroup(
            usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersLayout.createSequentialGroup()
                        .addComponent(userIcon)
                        .addGap(12, 12, 12)
                        .addComponent(usersTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(usersLayout.createSequentialGroup()
                        .addGroup(usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(usersOp7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usersOp4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usersOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usersOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        usersLayout.setVerticalGroup(
            usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usersTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usersOp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usersOp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usersOp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersOp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spnl_user.setViewportView(users);

        pnl_cont.add(spnl_user, "card2");

        spnl_device.setBorder(null);

        devices.setBackground(new java.awt.Color(255, 255, 255));

        deviceTitle1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        deviceTitle1.setText("Dispositivos");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/pc-icon-grey.png"))); // NOI18N

        deviceOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp1MouseExited(evt);
            }
        });

        lbl_op21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op21.setText("Buscar dispositivo");
        lbl_op21.setToolTipText("search device");
        lbl_op21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op21MouseEntered(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/seedevice.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp1Layout = new javax.swing.GroupLayout(deviceOp1);
        deviceOp1.setLayout(deviceOp1Layout);
        deviceOp1Layout.setHorizontalGroup(
            deviceOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op21, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp1Layout.setVerticalGroup(
            deviceOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op21)
                .addContainerGap())
        );

        deviceOp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp2MouseExited(evt);
            }
        });

        lbl_op22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op22.setText("Agregar dispositivo");
        lbl_op22.setToolTipText("add device");
        lbl_op22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op22MouseEntered(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/adddevice.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp2Layout = new javax.swing.GroupLayout(deviceOp2);
        deviceOp2.setLayout(deviceOp2Layout);
        deviceOp2Layout.setHorizontalGroup(
            deviceOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op22, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp2Layout.setVerticalGroup(
            deviceOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_op22)
                .addContainerGap())
        );

        deviceOp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp3MouseExited(evt);
            }
        });

        lbl_op23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op23.setText("Agregar nueva categoria");
        lbl_op23.setToolTipText("add category");
        lbl_op23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op23MouseEntered(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/addcategory.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp3Layout = new javax.swing.GroupLayout(deviceOp3);
        deviceOp3.setLayout(deviceOp3Layout);
        deviceOp3Layout.setHorizontalGroup(
            deviceOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op23, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp3Layout.setVerticalGroup(
            deviceOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        deviceOp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp4MouseExited(evt);
            }
        });

        lbl_op24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op24.setText("Asignar dispositivo");
        lbl_op24.setToolTipText("assign device");
        lbl_op24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op24MouseEntered(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/assignment.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp4Layout = new javax.swing.GroupLayout(deviceOp4);
        deviceOp4.setLayout(deviceOp4Layout);
        deviceOp4Layout.setHorizontalGroup(
            deviceOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op24, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp4Layout.setVerticalGroup(
            deviceOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        deviceOp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp5MouseExited(evt);
            }
        });

        lbl_op25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op25.setText("Editar dispositivo");
        lbl_op25.setToolTipText("edit device");
        lbl_op25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op25MouseEntered(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/editdevice.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp5Layout = new javax.swing.GroupLayout(deviceOp5);
        deviceOp5.setLayout(deviceOp5Layout);
        deviceOp5Layout.setHorizontalGroup(
            deviceOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op25, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp5Layout.setVerticalGroup(
            deviceOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op25)
                .addContainerGap())
        );

        deviceOp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp6MouseExited(evt);
            }
        });

        lbl_op26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op26.setText("Eliminar dispositivo");
        lbl_op26.setToolTipText("delete device");
        lbl_op26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op26MouseEntered(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/deletedevice.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp6Layout = new javax.swing.GroupLayout(deviceOp6);
        deviceOp6.setLayout(deviceOp6Layout);
        deviceOp6Layout.setHorizontalGroup(
            deviceOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op26, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp6Layout.setVerticalGroup(
            deviceOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op26)
                .addContainerGap())
        );

        deviceOp7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp7MouseExited(evt);
            }
        });

        lbl_op27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op27.setText("Eliminar categoria");
        lbl_op27.setToolTipText("delete category");
        lbl_op27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op27MouseEntered(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/deletecategory.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp7Layout = new javax.swing.GroupLayout(deviceOp7);
        deviceOp7.setLayout(deviceOp7Layout);
        deviceOp7Layout.setHorizontalGroup(
            deviceOp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(lbl_op27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp7Layout.setVerticalGroup(
            deviceOp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op27)
                .addContainerGap())
        );

        deviceOp8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceOp8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceOp8MouseExited(evt);
            }
        });

        lbl_op28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op28.setText("Devolver dispositivo");
        lbl_op28.setToolTipText("end assign");
        lbl_op28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op28MouseEntered(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/unassign.png"))); // NOI18N

        javax.swing.GroupLayout deviceOp8Layout = new javax.swing.GroupLayout(deviceOp8);
        deviceOp8.setLayout(deviceOp8Layout);
        deviceOp8Layout.setHorizontalGroup(
            deviceOp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOp8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        deviceOp8Layout.setVerticalGroup(
            deviceOp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deviceOp8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lbl_op28)
                .addContainerGap())
        );

        javax.swing.GroupLayout devicesLayout = new javax.swing.GroupLayout(devices);
        devices.setLayout(devicesLayout);
        devicesLayout.setHorizontalGroup(
            devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(devicesLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deviceTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(devicesLayout.createSequentialGroup()
                        .addComponent(deviceOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deviceOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(deviceOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(devicesLayout.createSequentialGroup()
                        .addGroup(devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deviceOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deviceOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deviceOp8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deviceOp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deviceOp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        devicesLayout.setVerticalGroup(
            devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deviceTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deviceOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceOp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceOp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deviceOp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceOp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceOp7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(devicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deviceOp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceOp8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        spnl_device.setViewportView(devices);

        pnl_cont.add(spnl_device, "card3");

        spnl_reports.setBorder(null);

        reports.setBackground(new java.awt.Color(255, 255, 255));

        reportTitle.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        reportTitle.setText("Reportes");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/report-icon.png"))); // NOI18N

        reportOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportOp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportOp1MouseExited(evt);
            }
        });

        lbl_op31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op31.setText("Reportar avería");
        lbl_op31.setToolTipText("report fault");
        lbl_op31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op31MouseEntered(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/addReport.png"))); // NOI18N

        javax.swing.GroupLayout reportOp1Layout = new javax.swing.GroupLayout(reportOp1);
        reportOp1.setLayout(reportOp1Layout);
        reportOp1Layout.setHorizontalGroup(
            reportOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op31, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        reportOp1Layout.setVerticalGroup(
            reportOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportOp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_op31)
                .addContainerGap())
        );

        reportOp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportOp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportOp2MouseExited(evt);
            }
        });

        lbl_op32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op32.setText("Avería solucionada");
        lbl_op32.setToolTipText("fixed fault");
        lbl_op32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op32MouseEntered(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/fixReport.png"))); // NOI18N

        javax.swing.GroupLayout reportOp2Layout = new javax.swing.GroupLayout(reportOp2);
        reportOp2.setLayout(reportOp2Layout);
        reportOp2Layout.setHorizontalGroup(
            reportOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportOp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op32, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        reportOp2Layout.setVerticalGroup(
            reportOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportOp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op32)
                .addContainerGap())
        );

        reportOp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportOp3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportOp3MouseExited(evt);
            }
        });

        lbl_op33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op33.setText("Buscar avería");
        lbl_op33.setToolTipText("search fault");
        lbl_op33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op33MouseEntered(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/seeReport.png"))); // NOI18N

        javax.swing.GroupLayout reportOp3Layout = new javax.swing.GroupLayout(reportOp3);
        reportOp3.setLayout(reportOp3Layout);
        reportOp3Layout.setHorizontalGroup(
            reportOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportOp3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op33, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        reportOp3Layout.setVerticalGroup(
            reportOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportOp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op33)
                .addContainerGap())
        );

        javax.swing.GroupLayout reportsLayout = new javax.swing.GroupLayout(reports);
        reports.setLayout(reportsLayout);
        reportsLayout.setHorizontalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportsLayout.createSequentialGroup()
                        .addComponent(reportOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(reportsLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        reportsLayout.setVerticalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportOp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportOp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        spnl_reports.setViewportView(reports);

        pnl_cont.add(spnl_reports, "card4");

        spnl_contacts.setBorder(null);

        contacts.setBackground(new java.awt.Color(255, 255, 255));

        contacts_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/phone.png"))); // NOI18N

        contacts_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        contacts_title.setText("Contactos");

        lbl_op41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op41.setText("Agregar proveedor");
        lbl_op41.setToolTipText("add provider");
        lbl_op41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/addIphone.png"))); // NOI18N

        javax.swing.GroupLayout contactsOp1Layout = new javax.swing.GroupLayout(contactsOp1);
        contactsOp1.setLayout(contactsOp1Layout);
        contactsOp1Layout.setHorizontalGroup(
            contactsOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactsOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactsOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op41, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        contactsOp1Layout.setVerticalGroup(
            contactsOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactsOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lbl_op41)
                .addContainerGap())
        );

        lbl_op42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op42.setText("Eliminar proveedor");
        lbl_op42.setToolTipText("delete provider");
        lbl_op42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/deleteIphone.png"))); // NOI18N

        javax.swing.GroupLayout contactsOp2Layout = new javax.swing.GroupLayout(contactsOp2);
        contactsOp2.setLayout(contactsOp2Layout);
        contactsOp2Layout.setHorizontalGroup(
            contactsOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactsOp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactsOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op42, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contactsOp2Layout.setVerticalGroup(
            contactsOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactsOp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op42)
                .addContainerGap())
        );

        lbl_op43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op43.setText("Buscar proveedor");
        lbl_op43.setToolTipText("search provider");
        lbl_op43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/seeIphone.png"))); // NOI18N

        javax.swing.GroupLayout contactsOp3Layout = new javax.swing.GroupLayout(contactsOp3);
        contactsOp3.setLayout(contactsOp3Layout);
        contactsOp3Layout.setHorizontalGroup(
            contactsOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactsOp3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactsOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_op43, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contactsOp3Layout.setVerticalGroup(
            contactsOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactsOp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_op43)
                .addContainerGap())
        );

        javax.swing.GroupLayout contactsLayout = new javax.swing.GroupLayout(contacts);
        contacts.setLayout(contactsLayout);
        contactsLayout.setHorizontalGroup(
            contactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contactsLayout.createSequentialGroup()
                        .addComponent(contactsOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contactsOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contactsOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contactsLayout.createSequentialGroup()
                        .addComponent(contacts_img)
                        .addGap(12, 12, 12)
                        .addComponent(contacts_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contactsLayout.setVerticalGroup(
            contactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contacts_title)
                    .addComponent(contacts_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(contactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contactsOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactsOp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactsOp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        spnl_contacts.setViewportView(contacts);

        pnl_cont.add(spnl_contacts, "card5");

        spnl_storehouse.setBorder(null);

        storehouse.setBackground(new java.awt.Color(255, 255, 255));

        storehouse_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/storehouse.png"))); // NOI18N

        storehouse_title.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        storehouse_title.setText("Almacen");

        storehouseOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                storehouseOp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                storehouseOp1MouseExited(evt);
            }
        });

        lbl_op51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_op51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_op51.setText("Información del almacen");
        lbl_op51.setToolTipText("info storehouse");
        lbl_op51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_op51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_op51MouseEntered(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/storehouse-big.png"))); // NOI18N

        javax.swing.GroupLayout storehouseOp1Layout = new javax.swing.GroupLayout(storehouseOp1);
        storehouseOp1.setLayout(storehouseOp1Layout);
        storehouseOp1Layout.setHorizontalGroup(
            storehouseOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storehouseOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storehouseOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_op51, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        storehouseOp1Layout.setVerticalGroup(
            storehouseOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storehouseOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lbl_op51)
                .addContainerGap())
        );

        javax.swing.GroupLayout storehouseLayout = new javax.swing.GroupLayout(storehouse);
        storehouse.setLayout(storehouseLayout);
        storehouseLayout.setHorizontalGroup(
            storehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storehouseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(storehouseOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(storehouseLayout.createSequentialGroup()
                        .addComponent(storehouse_img)
                        .addGap(12, 12, 12)
                        .addComponent(storehouse_title, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        storehouseLayout.setVerticalGroup(
            storehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storehouseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(storehouse_title)
                    .addComponent(storehouse_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(storehouseOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spnl_storehouse.setViewportView(storehouse);

        pnl_cont.add(spnl_storehouse, "card6");

        javax.swing.GroupLayout pnl_bgLayout = new javax.swing.GroupLayout(pnl_bg);
        pnl_bg.setLayout(pnl_bgLayout);
        pnl_bgLayout.setHorizontalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_cont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_bgLayout.setVerticalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addComponent(pnl_nav, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_cont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_op21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op21MouseEntered
        // TODO add your handling code here:
        lbl_op21.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op21MouseEntered

    private void deviceOp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp1MouseEntered
        // TODO add your handling code here:
        lbl_op21.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp1MouseEntered

    private void deviceOp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp1MouseExited
        // TODO add your handling code here:
        lbl_op21.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp1MouseExited

    private void lbl_op22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op22MouseEntered
        // TODO add your handling code here:op1.setForeground(new Color(0, 145, 234));
        lbl_op22.setForeground(Colors.lightBlue());
        
    }//GEN-LAST:event_lbl_op22MouseEntered

    private void deviceOp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp2MouseEntered
        // TODO add your handling code here:
        lbl_op22.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp2MouseEntered

    private void deviceOp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp2MouseExited
        // TODO add your handling code here:
        lbl_op22.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp2MouseExited

    private void lbl_op23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op23MouseEntered
        // TODO add your handling code here:
        lbl_op23.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op23MouseEntered

    private void deviceOp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp3MouseEntered
        // TODO add your handling code here:
        lbl_op23.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp3MouseEntered

    private void deviceOp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp3MouseExited
        // TODO add your handling code here:
        lbl_op23.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp3MouseExited

    private void lbl_op31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op31MouseEntered
        // TODO add your handling code here:
        lbl_op31.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op31MouseEntered

    private void reportOp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportOp1MouseEntered
        // TODO add your handling code here:
        lbl_op31.setForeground(Colors.lightBlue());
        
    }//GEN-LAST:event_reportOp1MouseEntered

    private void reportOp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportOp1MouseExited
        // TODO add your handling code here:
        lbl_op31.setForeground(Color.BLACK);
    }//GEN-LAST:event_reportOp1MouseExited

    private void lbl_op32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op32MouseEntered
        // TODO add your handling code here:
        lbl_op32.setForeground(Colors.lightBlue());
        
    }//GEN-LAST:event_lbl_op32MouseEntered

    private void reportOp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportOp2MouseEntered
        // TODO add your handling code here:
        lbl_op32.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_reportOp2MouseEntered

    private void reportOp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportOp2MouseExited
        // TODO add your handling code here:
        lbl_op32.setForeground(Color.BLACK);
    }//GEN-LAST:event_reportOp2MouseExited

    private void lbl_op24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op24MouseEntered
        // TODO add your handling code here:
        lbl_op24.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op24MouseEntered

    private void deviceOp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp4MouseEntered
        // TODO add your handling code here:
        lbl_op24.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp4MouseEntered

    private void deviceOp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp4MouseExited
        // TODO add your handling code here:
        lbl_op24.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp4MouseExited

    private void lbl_op25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op25MouseEntered
        // TODO add your handling code here:
        lbl_op25.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op25MouseEntered

    private void deviceOp5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp5MouseEntered
        // TODO add your handling code here:
        lbl_op25.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp5MouseEntered

    private void deviceOp5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp5MouseExited
        // TODO add your handling code here:
        lbl_op25.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp5MouseExited

    private void lbl_op26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op26MouseEntered
        // TODO add your handling code here:
        lbl_op26.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op26MouseEntered

    private void deviceOp6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp6MouseEntered
        // TODO add your handling code here:
        lbl_op26.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp6MouseEntered

    private void deviceOp6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp6MouseExited
        // TODO add your handling code here:
        lbl_op26.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp6MouseExited

    private void lbl_op33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op33MouseEntered
        // TODO add your handling code here:
        lbl_op33.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op33MouseEntered

    private void reportOp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportOp3MouseEntered
        // TODO add your handling code here:
        lbl_op33.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_reportOp3MouseEntered

    private void reportOp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportOp3MouseExited
        // TODO add your handling code here:
        lbl_op33.setForeground(Color.BLACK);
    }//GEN-LAST:event_reportOp3MouseExited

    private void lbl_op11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op11MouseEntered
        // TODO add your handling code here:
        lbl_op11.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op11MouseEntered

    private void lbl_op11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_op11MouseExited

    private void usersOp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp4MouseEntered
        // TODO add your handling code here:
        lbl_op11.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_usersOp4MouseEntered

    private void usersOp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp4MouseExited
        // TODO add your handling code here:
        lbl_op11.setForeground(Color.BLACK);
    }//GEN-LAST:event_usersOp4MouseExited

    private void lbl_op12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op12MouseEntered
        // TODO add your handling code here:
        lbl_op12.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op12MouseEntered

    private void lbl_op12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_op12MouseExited

    private void usersOp5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp5MouseEntered
        // TODO add your handling code here:
        lbl_op12.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_usersOp5MouseEntered

    private void usersOp5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp5MouseExited
        // TODO add your handling code here:
        lbl_op12.setForeground(Color.BLACK);
    }//GEN-LAST:event_usersOp5MouseExited

    private void lbl_op13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op13MouseEntered
        // TODO add your handling code here:
        lbl_op13.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op13MouseEntered

    private void lbl_op13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_op13MouseExited

    private void usersOp6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp6MouseEntered
        // TODO add your handling code here:
        lbl_op13.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_usersOp6MouseEntered

    private void usersOp6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp6MouseExited
        // TODO add your handling code here:
        lbl_op13.setForeground(Color.BLACK);
    }//GEN-LAST:event_usersOp6MouseExited

    private void lbl_op14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op14MouseEntered
        // TODO add your handling code here:
        lbl_op14.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op14MouseEntered

    private void lbl_op14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_op14MouseExited

    private void usersOp7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp7MouseEntered
        // TODO add your handling code here:
        lbl_op14.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_usersOp7MouseEntered

    private void usersOp7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersOp7MouseExited
        // TODO add your handling code here:
        lbl_op14.setForeground(Color.BLACK);
    }//GEN-LAST:event_usersOp7MouseExited

    private void deviceOp7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp7MouseEntered
        // TODO add your handling code here:
        lbl_op27.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp7MouseEntered

    private void deviceOp7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp7MouseExited
        // TODO add your handling code here:
        lbl_op27.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp7MouseExited

    private void deviceOp8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp8MouseEntered
        // TODO add your handling code here:
        lbl_op28.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_deviceOp8MouseEntered

    private void deviceOp8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOp8MouseExited
        // TODO add your handling code here:
        lbl_op28.setForeground(Color.BLACK);
    }//GEN-LAST:event_deviceOp8MouseExited

    private void lbl_op27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op27MouseEntered
        // TODO add your handling code here:
        lbl_op27.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op27MouseEntered

    private void lbl_op28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op28MouseEntered
        // TODO add your handling code here:
        lbl_op28.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op28MouseEntered

    private void storehouseOp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storehouseOp1MouseEntered
        // TODO add your handling code here:
        lbl_op51.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_storehouseOp1MouseEntered

    private void lbl_op51MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_op51MouseEntered
        // TODO add your handling code here:
        lbl_op51.setForeground(Colors.lightBlue());
    }//GEN-LAST:event_lbl_op51MouseEntered

    private void storehouseOp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storehouseOp1MouseExited
        // TODO add your handling code here:
        lbl_op51.setForeground(Color.BLACK);
    }//GEN-LAST:event_storehouseOp1MouseExited
    
    
    /**
     * @param args the command line arguments
     */
    
    public void selectButton(JLabel label) {
        label.setBackground(new Color(33,150,243));
    }
    
    public void unselectButtons() {
        
        Color unselect = new Color(0,99,177);
        lbl_users.setBackground(unselect);
        lbl_devices.setBackground(unselect);
        lbl_reports.setBackground(unselect);   
        lbl_contacts.setBackground(unselect);
        lbl_storehouse.setBackground(unselect);
    }
    
    public void hideAll(){
        spnl_user.hide();
        spnl_device.hide();
        spnl_reports.hide();
        spnl_contacts.hide();
        spnl_storehouse.hide();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contacts;
    private javax.swing.JPanel contactsOp1;
    private javax.swing.JPanel contactsOp2;
    private javax.swing.JPanel contactsOp3;
    private javax.swing.JLabel contacts_img;
    private javax.swing.JLabel contacts_title;
    private javax.swing.JPanel deviceOp1;
    private javax.swing.JPanel deviceOp2;
    private javax.swing.JPanel deviceOp3;
    private javax.swing.JPanel deviceOp4;
    private javax.swing.JPanel deviceOp5;
    private javax.swing.JPanel deviceOp6;
    private javax.swing.JPanel deviceOp7;
    private javax.swing.JPanel deviceOp8;
    private javax.swing.JLabel deviceTitle1;
    private javax.swing.JPanel devices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lbl_contacts;
    public javax.swing.JLabel lbl_devices;
    public javax.swing.JLabel lbl_logout;
    public javax.swing.JLabel lbl_op11;
    public javax.swing.JLabel lbl_op12;
    public javax.swing.JLabel lbl_op13;
    public javax.swing.JLabel lbl_op14;
    public javax.swing.JLabel lbl_op21;
    public javax.swing.JLabel lbl_op22;
    public javax.swing.JLabel lbl_op23;
    public javax.swing.JLabel lbl_op24;
    public javax.swing.JLabel lbl_op25;
    public javax.swing.JLabel lbl_op26;
    public javax.swing.JLabel lbl_op27;
    public javax.swing.JLabel lbl_op28;
    public javax.swing.JLabel lbl_op31;
    public javax.swing.JLabel lbl_op32;
    public javax.swing.JLabel lbl_op33;
    public javax.swing.JLabel lbl_op41;
    public javax.swing.JLabel lbl_op42;
    public javax.swing.JLabel lbl_op43;
    public javax.swing.JLabel lbl_op51;
    public javax.swing.JLabel lbl_reports;
    public javax.swing.JLabel lbl_storehouse;
    public javax.swing.JLabel lbl_users;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JPanel pnl_cont;
    private javax.swing.JPanel pnl_nav;
    private javax.swing.JPanel reportOp1;
    private javax.swing.JPanel reportOp2;
    private javax.swing.JPanel reportOp3;
    private javax.swing.JLabel reportTitle;
    private javax.swing.JPanel reports;
    public javax.swing.JScrollPane spnl_contacts;
    public javax.swing.JScrollPane spnl_device;
    public javax.swing.JScrollPane spnl_reports;
    public javax.swing.JScrollPane spnl_storehouse;
    public javax.swing.JScrollPane spnl_user;
    private javax.swing.JPanel storehouse;
    private javax.swing.JPanel storehouseOp1;
    private javax.swing.JLabel storehouse_img;
    private javax.swing.JLabel storehouse_title;
    private javax.swing.JLabel userIcon;
    private javax.swing.JPanel users;
    private javax.swing.JPanel usersOp4;
    private javax.swing.JPanel usersOp5;
    private javax.swing.JPanel usersOp6;
    private javax.swing.JPanel usersOp7;
    private javax.swing.JLabel usersTitle;
    // End of variables declaration//GEN-END:variables
}
